test_key:
  test_key1: test_value1
  test_key2: test_value2
  test_key3: test_value3

data_ingestion:
  url: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  root_dir_zip: artifacts/data_zip
  root_dir: artifacts/data

base_model_generator:
  base_model_path: artifacts/base_model/base_model.h5
  actual_model_path: artifacts/final_model/final_model.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_log_dir:  artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_file_path: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/trained_model.h5
  training_data_path: artifacts/data/Chicken-fecal-images