test_key:
  test_key1: test_value1
  test_key2: test_value2
  test_key3: test_value3

data_ingestion:
  url: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  root_dir_zip: artifcacts/data_zip
  root_dir: artifcacts/data